# docker-compose.yml
version: '3.8'
services:
  heroldbot:
    build: .
    container_name: heroldbot
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped